### PR TITLE
Add endpoints for K8S health check

### PR DESCRIPTION
**Pull request by tianshengsui**
Related [story #26](https://app.clubhouse.io/virtool/story/26/kubernetes-liveness-and-readiness-checks)

### CODE REVIEW

**Review by igboyes — CHANGES_REQUESTED** [review]
Place return simple JSON objects and add API tests for these. Example:
```python
{
  "alive": True
}
```

We may want to expand this response and I'd rather keep the content type JSON.

**Comment by BlakeASmith** [comment]
Are there going to be situations in which the Virtool API is alive but not ready? 

If not then we could get away with having only the /api/health/live endpoint. If this does occur 
then we should add some mechanism to change the servers "readiness" status within the code.

**Comment by BlakeASmith** [comment]
> Are there going to be situations in which the Virtool API is alive but not ready?
> 
> If not then we could get away with having only the /api/health/live endpoint. If this does occur
> then we should add some mechanism to change the servers "readiness" status within the code.

You could store a "ready" variable in the `Application` object's config as described [here](https://docs.aiohttp.org/en/stable/web_advanced.html#application-s-config). Then change the `/api/health/ready` route handler to somethinglike;

```python
async def handler(request):
	if request.config_dict["ready"]:
		# report that the server is ready (HTTP 200)
		...
	else:
		# report that the server is not ready (HTTP 500, or another status code)
```

**Comment by tianshengsui** [comment]
@BlakeASmith This looks good. I will do it.

**Review by BlakeASmith — APPROVED** [review]

**Comment by igboyes** [comment]
The `ready` value is never actually set and will always be `True`.

After your looking into this, I am not sure if it makes sense to merge. I think the `/api` endpoint could be used for both readiness and liveness. Agreed @tianshengsui and @BlakeASmith?

I will close for now if so.

**Comment by tianshengsui** [comment]
> The `ready` value is never actually set and will always be `True`.
> 
> After your looking into this, I am not sure if it makes sense to merge. I think the `/api` endpoint could be used for both readiness and liveness. Agreed @tianshengsui and @BlakeASmith?
> 
> I will close for now if so.

Yes, I agree.

**Pull request closed without merging**
