### PR TITLE
fix: rename id path parameter in uploads

### PR DESCRIPTION
**Pull request by ryanfang5**

### CODE REVIEW

**Review by igboyes — CHANGES_REQUESTED** [review]
I don't think `alias` is actually needed here since it is a path parameter, not a query parameter. Make sense?

**Comment by ryanfang5** [comment]
> I don't think `alias` is actually needed here since it is a path parameter, not a query parameter. Make sense?

I think it is still required as the path parameter must be the same name as in the view. The tests are failing without `alias` for me.

**Comment by igboyes** [comment]
@ryanfang5 I think the following change is acceptable to make things clearer:
```py
@routes.view("/uploads/{upload_id}")
```
It is the same thing we do everywhere else.

**Comment by ryanfang5** [comment]
Experienced transient transaction error in`test_import_reference_task`, added pytest rerun which should fix it.

**Comment by ryanfang5** [comment]
@igboyes Getting a API rate limit exceeded error, not sure what should be done about this.

**Pull request merged**
